apiVersion: v1
kind: Service
metadata:
  name: search-halal-place
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: search-halal-place